// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {task} from '../models';

export function AddRepo(arg1:main.RepoEntry):Promise<void>;

export function AssignTask(arg1:string,arg2:string):Promise<task.Task>;

export function CreateTask(arg1:main.CreateTaskInput):Promise<task.Task>;

export function GetActiveRepoName():Promise<string>;

export function GetBoard(arg1:main.BoardFilter):Promise<main.BoardData>;

export function GetRepos():Promise<Array<main.RepoEntry>>;

export function GetTask(arg1:string):Promise<task.Task>;

export function GetTemplate(arg1:string):Promise<string>;

export function MoveTask(arg1:string,arg2:string):Promise<task.Task>;

export function RemoveRepo(arg1:string):Promise<void>;

export function SwitchRepo(arg1:string):Promise<void>;

export function UpdateTask(arg1:main.UpdateTaskInput):Promise<task.Task>;
