// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function AssignTask(arg1, arg2) {
  return window['go']['main']['App']['AssignTask'](arg1, arg2);
}

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function EnhanceDraft(arg1, arg2) {
  return window['go']['main']['App']['EnhanceDraft'](arg1, arg2);
}

export function EnhanceTask(arg1) {
  return window['go']['main']['App']['EnhanceTask'](arg1);
}

export function GetActiveRepoName() {
  return window['go']['main']['App']['GetActiveRepoName']();
}

export function GetBoard(arg1) {
  return window['go']['main']['App']['GetBoard'](arg1);
}

export function GetRepos() {
  return window['go']['main']['App']['GetRepos']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function MoveTask(arg1, arg2) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2);
}

export function RemoveRepo(arg1) {
  return window['go']['main']['App']['RemoveRepo'](arg1);
}

export function SwitchRepo(arg1) {
  return window['go']['main']['App']['SwitchRepo'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
